// S.P.A.R.K. — Analytics paylaşımlı StyleSheet
// Faz 0: analytics.tsx'ten çıkarıldı. Parent bir kez useMemo([scheme]) ile
// üretip kart bileşenlerine `styles` prop'u olarak geçer (tek örnek, P10/P12).
import { StyleSheet, Platform } from 'react-native';
import { Colors } from '../../theme/colors';
import { Typography, FontFamily } from '../../theme/typography';
import { Spacing, ScreenPadding, BorderRadius } from '../../theme/spacing';

export const getAnalyticsStyles = () => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    paddingHorizontal: ScreenPadding.horizontal,
    paddingBottom: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Spacing.lg,
    gap: Spacing.sm,
  },
  title: {
    ...Typography.headlineLarge,
    color: Colors.textPrimary,
  },
  dateRange: {
    ...Typography.bodyMedium,
    color: Colors.textSecondary,
    marginTop: 4,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.round,
    padding: 4,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  tab: {
    flex: 1,
    minWidth: 0,
    paddingVertical: Spacing.sm,
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: BorderRadius.round,
  },
  tabActive: {
    backgroundColor: Colors.primary + '22', // translucent primary
  },
  tabText: {
    ...Typography.labelMedium,
    letterSpacing: 0,
    textAlign: 'center',
    width: '100%',
    ...(Platform.OS === 'android' ? { includeFontPadding: false } : null),
    color: Colors.textSecondary,
  },
  tabTextActive: {
    color: Colors.primary,
    fontFamily: FontFamily.bold,
  },
  customDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.md,
    marginBottom: Spacing.md,
    paddingHorizontal: Spacing.md,
  },
  customDateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Colors.surfaceLight,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  customDateText: {
    ...Typography.labelMedium,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
  },
  editToggleBtn: {
    padding: Spacing.sm,
    backgroundColor: Colors.surfaceLight,
    borderRadius: BorderRadius.round,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  editToggleBtnActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.cardBorder,
  },
  editSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.xs,
  },
  editSectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.primary,
  },
  editSectionTitle: {
    ...Typography.labelMedium,
    color: Colors.textSecondary,
    fontFamily: FontFamily.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 1,
    flex: 1,
  },
  editSectionCount: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    fontFamily: FontFamily.medium,
    backgroundColor: Colors.surfaceLight,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.round,
    overflow: 'hidden',
  },
  editCardChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    backgroundColor: Colors.surfaceLight,
    paddingVertical: Spacing.md,
    paddingLeft: Spacing.lg,
    paddingRight: Spacing.xxxl + Spacing.sm,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  editRemoveBtn: {
    marginRight: -Spacing.xs,
  },
  editCardLabel: {
    ...Typography.labelLarge,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
    flex: 1,
  },
  availableGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.xs,
  },
  availableChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: Colors.surfaceLight,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.round,
    borderWidth: 1,
    borderColor: Colors.border,
    borderStyle: 'dashed',
  },
  availableChipLabel: {
    ...Typography.labelMedium,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
  },
  editHint: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
    textAlign: 'center',
    marginTop: Spacing.xl,
    marginBottom: Spacing.md,
  },
  trendTitle: {
    ...Typography.labelMedium,
    color: Colors.textSecondary,
    marginBottom: Spacing.md,
  },
  section: {
    marginTop: Spacing.lg,
  },
  sectionTitle: {
    ...Typography.labelMedium,
    color: Colors.textSecondary,
    letterSpacing: 1.5,
    marginBottom: Spacing.md,
  },
  categoryRow: {
    flexDirection: 'row',
    gap: Spacing.md,
    paddingVertical: Spacing.xs,
  },
  categoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    backgroundColor: Colors.surface,
    padding: Spacing.sm,
    paddingRight: Spacing.lg,
    borderRadius: BorderRadius.round,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  pillIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillInfo: {
    justifyContent: 'center',
  },
  pillName: {
    ...Typography.labelMedium,
    color: Colors.textPrimary,
  },
  pillAmount: {
    ...Typography.bodySmall,
    color: Colors.textSecondary,
    marginTop: 2,
  },
  donutCard: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
  },
  donutCenter: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutTotal: {
    ...Typography.headlineMedium,
    color: Colors.textPrimary,
    fontFamily: FontFamily.bold,
  },
  donutLabel: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    marginTop: 2,
    textAlign: 'center',
  },
  donutSub: {
    ...Typography.labelMedium,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    marginTop: 2,
  },
  donutAnalysisContainer: {
    marginTop: Spacing.xl,
    paddingHorizontal: Spacing.xl,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  donutAnalysisText: {
    ...Typography.bodyMedium,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
    textAlign: 'center',
    lineHeight: 22,
  },
  donutAnalysisHint: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    textAlign: 'center',
  },
  // Top Transactions
  topTxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.sm,
    gap: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.divider,
  },
  topTxRank: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topTxRankText: {
    ...Typography.labelSmall,
    fontFamily: FontFamily.bold,
    color: Colors.textSecondary,
  },
  topTxCatIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topTxContent: {
    flex: 1,
  },
  topTxVendor: {
    ...Typography.bodyMedium,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
  },
  topTxDate: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
  },
  topTxAmount: {
    ...Typography.bodyMedium,
    fontFamily: FontFamily.bold,
  },
  // Vendor rows
  vendorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: Spacing.md,
    gap: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.divider,
  },
  newBadge: {
    position: 'absolute',
    top: -4,
    right: -6,
    backgroundColor: Colors.success,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 6,
    zIndex: 2,
  },
  newBadgeText: {
    fontSize: 8,
    fontFamily: FontFamily.bold,
    color: '#FFF',
    letterSpacing: 0.5,
  },
  vendorRowActive: {
    backgroundColor: Colors.surfaceLight,
    marginHorizontal: -Spacing.lg,
    paddingHorizontal: Spacing.lg,
    // Pressable + Android: borderRadius tek başına bazen kare zemin çizer;
    // overflow: 'hidden' ile arka plan köşeleri kart estetiğiyle uyumlu kırpılır.
    borderRadius: BorderRadius.xl,
    overflow: 'hidden',
  },
  vendorRowActiveNoDivider: {
    borderBottomWidth: 0,
  },
  vendorInfo: {
    flex: 1,
    gap: Spacing.xs,
  },
  vendorName: {
    ...Typography.bodyLarge,
    fontFamily: FontFamily.medium,
    color: Colors.textPrimary,
  },
  vendorBar: {
    height: 4,
    backgroundColor: Colors.surfaceLight,
    borderRadius: 2,
    overflow: 'hidden',
  },
  vendorBarFill: {
    height: '100%',
    borderRadius: 2,
  },
  vendorAmountCol: {
    alignItems: 'flex-end',
  },
  vendorAmount: {
    ...Typography.bodyLarge,
    fontFamily: FontFamily.semiBold,
    color: Colors.textPrimary,
  },
  vendorPercent: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
  },
  // Micro-analysis — no left margin so donut/legend fills full width
  microAnalysis: {
    backgroundColor: Colors.surfaceElevated,
    borderRadius: BorderRadius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.lg,
    marginTop: Spacing.sm,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.borderLight + '40',
  },
  microTitle: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    marginBottom: Spacing.md,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  microItem: {
    paddingVertical: Spacing.sm,
  },
  microItemContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: Spacing.md,
  },
  microItemMain: {
    flex: 1,
    gap: 4,
  },
  microItemPrimary: {
    ...Typography.bodyMedium,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
  },
  microItemSecondary: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
  },
  microItemPriceCol: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  microItemAmount: {
    ...Typography.bodyMedium,
    fontFamily: FontFamily.semiBold,
    color: Colors.textPrimary,
  },
  microItemDivider: {
    height: 1,
    backgroundColor: Colors.divider,
    opacity: 0.5,
    marginTop: Spacing.sm,
    marginLeft: 2,
  },
  // Vendor Donut Chart — full-width redesign
  vendorDonutSection: {
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  vendorDonutCenter: {
    alignItems: 'center',
    gap: 2,
    maxWidth: 120,
  },
  vendorDonutCenterPressed: {
    opacity: 0.88,
  },
  vendorDonutTotal: {
    ...Typography.headlineMedium,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
  },
  vendorDonutPct: {
    fontSize: 22,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
  },
  vendorDonutLabel: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    textAlign: 'center',
  },
  vendorDonutSub: {
    ...Typography.labelMedium,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    marginTop: 2,
  },
  // 2-column legend grid
  legendGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: Spacing.md,
    width: '100%',
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: '47%',
    borderRadius: BorderRadius.sm,
    borderWidth: 1,
    borderColor: 'transparent',
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: Colors.surfaceLight,
  },
  legendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  legendText: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    flex: 1,
  },
  legendPct: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    fontFamily: FontFamily.semiBold,
    flexShrink: 0,
  },
  expandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing.md,
    marginTop: Spacing.sm,
    gap: Spacing.xs,
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.md,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  expandButtonText: {
    ...Typography.labelMedium,
    color: Colors.primary,
    fontFamily: FontFamily.medium,
  },
  primaryCard: {
    borderColor: Colors.cardBorder,
    borderWidth: 1,
  },
  // ── A1: Monthly Comparison ──
  compareRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  compareBlock: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  compareDivider: {
    width: 1,
    height: 40,
    backgroundColor: Colors.divider,
    marginHorizontal: Spacing.md,
  },
  compareLabel: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
  },
  compareValue: {
    ...Typography.headlineSmall,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
    fontSize: 18,
  },
  deltaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.md,
    backgroundColor: Colors.surfaceLight,
  },
  deltaText: {
    ...Typography.labelMedium,
    fontFamily: FontFamily.semiBold,
  },
  deltaHint: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    marginLeft: 2,
  },
  compareBars: {
    marginTop: Spacing.md,
    gap: Spacing.sm,
  },
  compareBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  compareBarLabel: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    width: 70,
  },
  compareBarTrack: {
    flex: 1,
    height: 6,
    backgroundColor: Colors.surfaceLight,
    borderRadius: 3,
    overflow: 'hidden',
  },
  compareBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  // ── A2: Budget Summary ──
  budgetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  budgetIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  budgetPctBadge: {
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.round,
  },
  budgetPctText: {
    ...Typography.labelMedium,
    fontFamily: FontFamily.bold,
  },
  budgetAmounts: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  budgetSmLabel: {
    ...Typography.bodySmall,
    color: Colors.textSecondary,
    marginBottom: 4,
  },
  budgetAmountVal: {
    ...Typography.headlineSmall,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
    fontSize: 18,
  },
  budgetBarTrack: {
    height: 8,
    backgroundColor: Colors.surfaceLight,
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: Spacing.md,
  },
  budgetBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  budgetFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.divider,
  },
  budgetStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  budgetStatLabel: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
  },
  budgetStatVal: {
    ...Typography.labelMedium,
    fontFamily: FontFamily.semiBold,
    color: Colors.textPrimary,
  },
  emptyBudget: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    gap: Spacing.sm,
  },
  emptyBudgetTitle: {
    ...Typography.bodyLarge,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
  },
  emptyBudgetHint: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
  },
  // ── A6: Price Watch (kompakt grid) ──
  priceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  priceHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
  },
  priceHeaderStats: {
    flexDirection: 'row',
    gap: Spacing.xs,
  },
  priceStatChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.round,
    backgroundColor: Colors.surfaceLight,
  },
  priceStatChipText: {
    ...Typography.labelSmall,
    fontFamily: FontFamily.extraBold,
    fontSize: 11,
  },
  priceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  priceTile: {
    // 2 sütun (gap: Spacing.sm) — küçük ekranlarda % hesabı kırpılmaz.
    width: '48.5%',
  },
  priceTileInner: {
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 6,
    minHeight: 88,
  },
  priceTileBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: BorderRadius.round,
    alignSelf: 'flex-start',
  },
  priceTilePct: {
    ...Typography.labelMedium,
    fontFamily: FontFamily.extraBold,
    fontSize: 12,
  },
  priceTileName: {
    ...Typography.bodyMedium,
    fontFamily: FontFamily.semiBold,
    color: Colors.textPrimary,
    lineHeight: 18,
  },
  priceTileSub: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    fontFamily: FontFamily.medium,
  },
  priceTileArrow: {
    color: Colors.textMuted,
  },
  priceHint: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    textAlign: 'center',
    marginTop: Spacing.md,
  },
  // ── A7: Streak ──
  streakGrid: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  streakCard: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  streakCardPressed: {
    backgroundColor: Colors.surfaceLight,
    borderColor: Colors.cardBorder,
    transform: [{ scale: 0.98 }],
  },
  streakIconBg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  streakNumber: {
    ...Typography.headlineMedium,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
    fontSize: 24,
  },
  streakLabel: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    textAlign: 'center',
  },
  streakMsg: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Spacing.md,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.lg,
    backgroundColor: Colors.surfaceLight,
    borderRadius: BorderRadius.md,
    gap: Spacing.xxl,
  },
  streakMsgRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    flex: 1,
    minWidth: 0,
  },
  streakMsgIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  streakMsgText: {
    fontFamily: FontFamily.extraBold,
    fontSize: 16,
    letterSpacing: 0.5,
    color: Colors.textPrimary,
    flex: 1,
    minWidth: 0,
  },
  // Marquee kapsayıcısı içindeki metin (flex YOK — doğal genişlik ölçülebilsin)
  streakMsgTextInner: {
    fontFamily: FontFamily.extraBold,
    fontSize: 16,
    letterSpacing: 0.5,
    color: Colors.textPrimary,
  },
  streakMsgSubWrap: {
    flexShrink: 0,
    paddingLeft: Spacing.md,
  },
  streakMsgSub: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
  },

  // ── A8: Month-end Projection ──
  projHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.lg,
  },
  projHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  projHeaderIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  projDaysChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.round,
  },
  projDaysChipText: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.semiBold,
    fontSize: 11,
  },
  projHeroLabel: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  projHeroValue: {
    fontSize: 36,
    lineHeight: 42,
    fontFamily: FontFamily.bold,
    letterSpacing: -0.5,
  },
  projPaceHint: {
    ...Typography.bodySmall,
    color: Colors.textSecondary,
    marginTop: 4,
  },
  projTrackWrap: {
    marginTop: Spacing.lg,
    marginBottom: Spacing.md,
  },
  projTrack: {
    height: 8,
    backgroundColor: Colors.surfaceLight,
    borderRadius: 4,
    overflow: 'hidden',
    position: 'relative',
  },
  projTrackCurrent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 4,
  },
  projTrackProjected: {
    position: 'absolute',
    top: 0,
    bottom: 0,
  },
  projTrackBudgetMarker: {
    position: 'absolute',
    top: -3,
    bottom: -3,
    width: 2,
    backgroundColor: Colors.textPrimary,
    borderRadius: 1,
  },
  projTrackLegend: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
    marginTop: Spacing.sm,
  },
  projLegendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  projLegendDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  projLegendDotBudget: {
    width: 2,
    height: 10,
    borderRadius: 1,
    backgroundColor: Colors.textPrimary,
  },
  projLegendText: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    fontSize: 11,
  },
  projOutcomePanel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginTop: Spacing.md,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
  },
  projOutcomeIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  projOutcomeTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  projOutcomeTitle: {
    ...Typography.bodyMedium,
    fontFamily: FontFamily.bold,
    fontSize: 14,
  },
  projOutcomeSub: {
    ...Typography.bodySmall,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
    lineHeight: 18,
  },
  projPaceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: Spacing.md,
    paddingTop: Spacing.md,
    borderTopWidth: 1,
    borderTopColor: Colors.divider,
  },
  projPaceRowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  projPaceLabel: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
  },
  projPaceValue: {
    ...Typography.bodyMedium,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
  },
  projEmptyWrap: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    gap: Spacing.sm,
  },
  projEmptyText: {
    ...Typography.bodyMedium,
    color: Colors.textMuted,
    textAlign: 'center',
  },
  projOutlierNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: Spacing.sm,
  },
  projOutlierNoteText: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    flex: 1,
    lineHeight: 15,
  },

  // ── A9: Active Subscriptions ──
  subsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  subsHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  subsHeaderIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subsCountBadge: {
    minWidth: 26,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: BorderRadius.round,
    alignItems: 'center',
  },
  subsCountText: {
    ...Typography.labelSmall,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
    fontSize: 11,
  },
  subsHeroBlock: {
    marginBottom: Spacing.lg,
  },
  subsHeroLabel: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  subsHeroValue: {
    fontSize: 30,
    lineHeight: 36,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
    letterSpacing: -0.5,
  },
  subsUpcomingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  subsUpcomingLabel: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.semiBold,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    fontSize: 10,
  },
  subsDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: Colors.divider,
  },
  subsList: {
    gap: 4,
  },
  subsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  subsAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  subsRowMain: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  subsRowName: {
    ...Typography.bodyMedium,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
  },
  subsRowMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  subsRowDays: {
    ...Typography.labelSmall,
    fontFamily: FontFamily.medium,
    fontSize: 11,
  },
  subsRowAmount: {
    ...Typography.bodyMedium,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
  },
  subsEmptyWrap: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    gap: Spacing.xs,
  },
  subsEmptyTitle: {
    ...Typography.bodyLarge,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    marginTop: Spacing.xs,
  },
  subsEmptyHint: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
    textAlign: 'center',
    paddingHorizontal: Spacing.lg,
  },

  // ── A10: Category Limits Health ──
  limitsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  limitsHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  limitsHeaderIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  limitsHeaderStats: {
    flexDirection: 'row',
    gap: Spacing.xs,
  },
  limitsStatChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    borderRadius: BorderRadius.round,
  },
  limitsStatChipText: {
    ...Typography.labelSmall,
    fontFamily: FontFamily.extraBold,
    fontSize: 11,
  },
  limitsList: {
    gap: Spacing.md,
  },
  limitRow: {
    gap: 6,
  },
  limitRowTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  limitIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  limitName: {
    ...Typography.bodyMedium,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
    flex: 1,
    minWidth: 0,
  },
  limitPct: {
    ...Typography.labelMedium,
    fontFamily: FontFamily.bold,
    fontSize: 13,
  },
  limitTrack: {
    height: 6,
    backgroundColor: Colors.surfaceLight,
    borderRadius: 3,
    overflow: 'hidden',
  },
  limitTrackFill: {
    height: '100%',
    borderRadius: 3,
  },
  limitRowBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  limitAmounts: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
  },
  limitSpent: {
    color: Colors.textPrimary,
    fontFamily: FontFamily.semiBold,
  },
  limitDiv: {
    color: Colors.textMuted,
  },
  limitMax: {
    color: Colors.textMuted,
    fontFamily: FontFamily.medium,
  },
  limitRemaining: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    fontSize: 11,
  },
  limitsEmptyWrap: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    gap: Spacing.xs,
  },
  limitsEmptyTitle: {
    ...Typography.bodyLarge,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    marginTop: Spacing.xs,
  },
  limitsEmptyHint: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
    textAlign: 'center',
    paddingHorizontal: Spacing.lg,
  },

  // ── A11: Savings Goal ──
  goalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  goalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  goalHeaderIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalDateChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.round,
  },
  goalDateChipText: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.semiBold,
    fontSize: 11,
  },
  goalTitle: {
    ...Typography.bodyLarge,
    color: Colors.textPrimary,
    fontFamily: FontFamily.semiBold,
    marginBottom: Spacing.md,
  },
  goalBody: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.lg,
    marginBottom: Spacing.md,
  },
  goalDonutWrap: {
    width: 140,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalDonutCenter: {
    alignItems: 'center',
    gap: 2,
  },
  goalDonutPct: {
    fontSize: 26,
    fontFamily: FontFamily.bold,
    letterSpacing: -0.5,
  },
  goalDonutLabel: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  goalStats: {
    flex: 1,
    gap: Spacing.sm,
    justifyContent: 'center',
  },
  goalStatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  goalStatDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  goalStatLabel: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    flex: 1,
  },
  goalStatValue: {
    ...Typography.labelMedium,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
  },
  goalOutcome: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.md,
    borderRadius: BorderRadius.lg,
    borderWidth: 1,
  },
  goalOutcomeIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalOutcomeText: {
    ...Typography.bodySmall,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
    flex: 1,
    lineHeight: 18,
  },
  goalEmptyWrap: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    gap: Spacing.xs,
  },
  goalEmptyTitle: {
    ...Typography.bodyLarge,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    marginTop: Spacing.xs,
  },
  goalEmptyHint: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
    textAlign: 'center',
    paddingHorizontal: Spacing.lg,
  },

  // ── A12: Time-of-day Heatmap ──
  todHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
    gap: Spacing.sm,
  },
  todHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  todHeaderIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todPeakChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 4,
    borderRadius: BorderRadius.round,
  },
  todPeakChipText: {
    ...Typography.labelSmall,
    color: Colors.primary,
    fontFamily: FontFamily.semiBold,
    fontSize: 11,
  },
  todGridWrap: {
    gap: 4,
    marginBottom: Spacing.md,
  },
  todGridHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  todGridRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  todDayLabelCell: {
    width: 32,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  todDayLabelText: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    fontSize: 11,
  },
  todSlotHeaderCell: {
    flex: 1,
    alignItems: 'center',
  },
  todSlotHeaderText: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    fontFamily: FontFamily.medium,
    fontSize: 10,
  },
  todCell: {
    flex: 1,
    height: 26,
    borderRadius: 6,
  },
  todCellPeak: {
    borderWidth: 2,
    borderColor: Colors.primary,
  },
  todDisclaimer: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    textAlign: 'center',
    fontSize: 11,
  },
  todEmptyWrap: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    gap: Spacing.xs,
  },
  todEmptyTitle: {
    ...Typography.bodyLarge,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    marginTop: Spacing.xs,
  },
  todEmptyHint: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
    textAlign: 'center',
    paddingHorizontal: Spacing.lg,
  },

  // ── A13: Silent Spend ──
  silentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  silentHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  silentHeaderIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  silentHeroBlock: {
    marginBottom: Spacing.sm,
  },
  silentHeroLabel: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  silentHeroValue: {
    fontSize: 30,
    lineHeight: 36,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
    letterSpacing: -0.5,
  },
  silentHeroMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: 4,
  },
  silentHeroMetaText: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
  },
  silentHeroMetaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: Colors.textMuted,
  },
  silentHint: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
    fontFamily: FontFamily.medium,
    marginTop: Spacing.sm,
    marginBottom: Spacing.md,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
    backgroundColor: Colors.surfaceLight,
    borderRadius: BorderRadius.md,
    lineHeight: 18,
  },
  silentList: {
    gap: 2,
  },
  silentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  silentAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  silentRowMain: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  silentRowName: {
    ...Typography.bodyMedium,
    color: Colors.textPrimary,
    fontFamily: FontFamily.medium,
  },
  silentRowMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  silentRowTimes: {
    ...Typography.labelSmall,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    fontSize: 11,
  },
  silentRowMetaDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: Colors.textMuted,
  },
  silentRowAvg: {
    ...Typography.labelSmall,
    color: Colors.textMuted,
    fontSize: 11,
  },
  silentRowTotal: {
    ...Typography.bodyMedium,
    fontFamily: FontFamily.bold,
    color: Colors.textPrimary,
  },
  silentEmptyWrap: {
    alignItems: 'center',
    paddingVertical: Spacing.xl,
    gap: Spacing.xs,
  },
  silentEmptyTitle: {
    ...Typography.bodyLarge,
    color: Colors.textSecondary,
    fontFamily: FontFamily.medium,
    marginTop: Spacing.xs,
  },
  silentEmptyHint: {
    ...Typography.bodySmall,
    color: Colors.textMuted,
    textAlign: 'center',
    paddingHorizontal: Spacing.lg,
  },
});

export type AnalyticsStyles = ReturnType<typeof getAnalyticsStyles>;
